export const QUOTES = [
  "The secret of getting ahead is getting started.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Success is the sum of small efforts repeated day in and day out.",
  "The future depends on what you do today.",
  "A little progress each day adds up to big results.",
  "Dream big. Start small. Act now.",
  "Consistency is what transforms average into excellence.",
  "Your only limit is you.",
  "Do something today that your future self will thank you for.",
  "Strive for progress, not perfection.",
  "The way to get started is to quit talking and begin doing.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Small steps every day.",
  "Push yourself because no one else is going to do it for you.",
  "If you’re tired of starting over, stop giving up.",
  "Great things never come from comfort zones.",
  "The key to success is to focus on goals, not obstacles.",
  "Stay positive, work hard, make it happen.",
  "Believe you can and you’re halfway there.",
  "The expert in anything was once a beginner.",
  "It always seems impossible until it’s done.",
  "Start where you are. Use what you have. Do what you can.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The distance between dreams and reality is called action.",
  "Your passion is waiting for your courage to catch up.",
  "Believe in yourself and all that you are.",
  "You are capable of more than you know.",
  "Start each day with a positive thought.",
  "The harder the conflict, the greater the triumph.",
  "Success is not for the lazy.",
  "You don’t need to see the whole staircase, just take the first step.",
  "Action is the foundational key to all success.",
  "Failure is not falling down, but refusing to get up.",
  "The only time you fail is when you fall down and stay down.",
  "The more you give, the more you get.",
  "A goal without a plan is just a wish.",
  "Focus on being productive instead of busy.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Don’t let yesterday take up too much of today.",
  "If you want it, work for it.",
  "The secret to getting ahead is to start.",
  "Start with what you have. Do what you can.",
  "Good things come to those who work for it.",
  "Discipline is the bridge between goals and accomplishments.",
  "The only bad workout is the one that didn’t happen.",
  "Success is the best revenge.",
  "Chase your dreams, but always know the road that will lead you home.",
  "Learning is a treasure that will follow its owner everywhere.",
]
