export const QUOTES = [
  "You do not rise to the level of your goals. You fall to the level of your systems. — James Clear",
  "Every action you take is a vote for the type of person you wish to become. — James Clear",
  "Progress requires unlearning. Becoming the best version of yourself requires you to continuously edit your beliefs, and to upgrade and expand your identity. — James Clear",
  "Your outcomes are a lagging measure of your habits. Your net worth is a lagging measure of your financial habits. Your knowledge is a lagging measure of your learning habits. You get what you repeat. — James Clear",
  "The greatest threat to success is not failure but boredom. — James Clear",
  "You should be far more concerned with your current trajectory than with your current results. — James Clear",
  "Be the designer of your world and not merely the consumer of it. — James Clear",
  "The most practical way to change who you are is to change what you do. — James Clear",
  "The greatest superpower is the ability to change yourself. — Naval Ravikant",
  "You make your own luck if you stay at it long enough. — Naval Ravikant",
  "A fit body, a calm mind, a house full of love. These things cannot be bought — they must be earned. — Naval Ravikant",
  "All the real benefits in life come from compound interest. — Naval Ravikant",
  "If you learn how to learn, it's the ultimate meta skill. — Naval Ravikant",
  "The means of learning are abundant, the desire to learn is scarce. — Naval Ravikant",
  "Reading is the ultimate meta-skill that can be traded for anything else. — Naval Ravikant",
  "No one can compete with you on being you. — Naval Ravikant",
  "Stop caring about the impact and just be the best version of you possible — then you'll naturally have an impact. — Naval Ravikant",
  "A busy calendar and a busy mind will destroy your ability to create anything great. — Naval Ravikant",
  "You should never sacrifice what you could be for what you are. — Jordan Peterson",
  "The purpose of life is finding the largest burden that you can bear and bearing it. — Jordan Peterson",
  "To stand up straight with your shoulders back is to accept the terrible responsibility of life, with eyes wide open. — Jordan Peterson",
  "You're going to pay a price for every bloody thing you do and everything you don't do. You don't get to choose to not pay a price. You get to choose which poison you're going to take. — Jordan Peterson",
  "You can only find out what you actually believe by watching how you act. You simply don't know what you believe, before that. — Jordan Peterson",
  "If you don't say what you think then you kill your unborn self. — Jordan Peterson",
  "The successful among us delay gratification. The successful among us bargain with the future. — Jordan Peterson",
  "In the morning when thou risest unwillingly, let this thought be present: I am rising to the work of a human being. — Marcus Aurelius",
  "Our plans miscarry because they have no aim. When a man does not know what harbour he is making for, no wind is the right wind. — Seneca",
  "The spirit ought to be brought up for examination daily. — Seneca",
  "Men are disturbed, not by Things, but by the Principles and Notions, which they form concerning Things. — Epictetus",
  "Require not Things to happen as you wish; but wish them to happen as they do happen; and you will go on well. — Epictetus",
  "He who is living without discipline is exposed to grievous ruin. Who hath a harder battle to fight than he who striveth for self-mastery? — Thomas à Kempis",
  "You will never have a greater or lesser dominion than that over yourself. The height of a man's success is gauged by his self-mastery; the depth of his failure by his self-abandonment. — Leonardo da Vinci",
  "Rule your mind or it will rule you. — Horace",
  "Freedom is born of self-discipline. No individual, no nation, can achieve or maintain liberty without self-control. — Alan Valentine",
  "The bridge between wishing and accomplishing is discipline. — Harvey Mackay",
  "Your ability to discipline yourself to set clear goals, and then to work toward them everyday, will do more to guarantee your success than any other single factor. — Brian Tracy",
  "The ability to subordinate an impulse to a value is the essence of the proactive person. — Stephen Covey",
  "Success is actually a short race — a sprint fueled by discipline just long enough for habit to kick in and take over. — Gary Keller",
  "In essence, if we want to direct our lives, we must take control of our consistent actions. It's not what we do once in a while that shapes our lives, but what we do consistently. — Tony Robbins",
  "Small disciplines repeated with consistency every day lead to great achievements gained slowly over time. — John C. Maxwell",
  "People do not decide their futures, they decide their habits and their habits decide their futures. — F. Matthias Alexander",
  "Build the habits that shape your future, not the ones that entertain your present. — James Clear",
  "You aren't afraid of failure. You are afraid of replacing the mediocre habits and routines that your brain loves so much. — Dan Koe",
  "Fast, lift, sprint, stretch, and meditate. Build, sell, write, create, invest, and own. Read, reflect, love, seek truth, and ignore society. Make these habits. Say no to everything else. — Naval Ravikant",
  "Watch someone's daily habits today and you will understand what their future looks like. — Anthony Pompliano",
  "Success leaves clues, but they're rarely in inspirational quotes. They're in the unsexy habits successful people maintain when motivation dies. — Dan Martell",
  "The most powerful habit you can adopt: Using the first hour of your day to build, write, or produce something of value. — Dan Koe",
  "Doing hard things is a habit that must be practiced, or, like all habits, it will be lost. — Mark Manson",
  "The life you want starts with the habits you repeat when no one's watching. — Lewis Howes",
  "When excellence becomes a habit, then that's just who you are. — Kobe Bryant",
  "Habit formation is the art of becoming someone new. — James Clear",
]