export const QUOTES =[
  "You become what you repeatedly tolerate.",
  "Discipline is remembering what you want most instead of what you want now.",
  "The obstacle does not ask for your opinion; it asks for your response.",
  "A calm mind is a sharper weapon than a loud voice.",
  "Your habits are voting for the person you become.",
  "Nothing steals more years than postponing the life you already know you should live.",
  "Comfort is a beautiful place to visit, but a dangerous place to settle.",
  "The quality of your life is hidden inside the quality of your attention.",
  "Master yourself before attempting to master your circumstances.",
  "What you refuse to face will eventually become your teacher.",
  "Freedom begins where the need for approval ends.",
  "The world rarely rewards potential; it rewards consistency.",
  "Your future is quietly negotiating with every decision you make today.",
  "Silence reveals what noise tries to hide.",
  "Strength is built by carrying what once felt unbearable.",
  "A person who cannot sit alone with their thoughts will eventually be ruled by them.",
  "You don't find purpose; you build it through repeated acts of responsibility.",
  "Every excuse is a promise to stay the same.",
  "Your greatest prison is the story you keep telling yourself.",
  "Time exposes every illusion that comfort protects.",
  "The hardest battles leave no visible scars.",
  "You cannot think your way into courage; you must act your way into it.",
  "Resentment is a debt you keep paying to the past.",
  "The strongest people are not unbreakable; they rebuild faster.",
  "What feels like sacrifice today often becomes freedom tomorrow.",
  "A peaceful mind is earned, not inherited.",
  "Your standards decide your future long before your goals do.",
  "Wisdom grows where certainty dies.",
  "The life you envy is usually built from decisions you avoid.",
  "Every morning you inherit a new chance but not a new lifetime.",
  "Character is what remains when ambition is exhausted.",
  "You suffer more from imagination than from reality.",
  "The cost of avoiding discomfort is a life without depth.",
  "Patience is confidence stretched across time.",
  "If your identity depends on success, failure will always own you.",
  "The person who governs their emotions is difficult to defeat.",
  "Peace is not found by controlling the world, but by controlling your reactions to it.",
  "Your attention is your most valuable possession; spend it deliberately.",
  "A meaningful life is rarely an easy one.",
  "Every day you delay the difficult conversation, the price increases.",
  "Clarity arrives through action more often than thought.",
  "The soul grows in proportion to the truth it is willing to accept.",
  "Small acts repeated without applause become extraordinary lives.",
  "You cannot outrun a mind you refuse to understand.",
  "The ego seeks victory; wisdom seeks understanding.",
  "Nothing is more expensive than a cheap compromise with your principles.",
  "The person you become is hidden inside the choices nobody else notices.",
  "Endurance is ambition that learned patience.",
  "A fulfilled life is measured less by what you gained than by what you no longer needed.",
  "Live in such a way that your conscience becomes your safest place."
]